# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Personal Web
email: info@antarg.co
description: This DIY guide aims to help you set up your own website so you can present yourself online in your own terms. The approach is iterative, so you can reap gains quick and dirty, and modular, so you can focus on quickly building only the functionalities you're most interested in.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: strangehill
url: "http://antarg.co" # the base hostname & protocol for your site
github_username:  strangehill

# Build settings
markdown: kramdown

collections:
  thesis:
    output: true
